apiVersion: v1
kind: Service
metadata:
  name: {{ include "helloworld-rev-service.fullname" . }}
  namespace: {{ .Values.service.namespace}}
spec:
  selector:
    app: {{ .Values.service.label }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP